# -*- coding: utf-8 -*-
"""Graph.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AXiYOx7aND5hN9Bbkk48syWE58xakBLs
"""

import matplotlib.pyplot as plt
import networkx as nx
from collections import deque

class GraphStructure:
    def __init__(self):
        self.graph = {}

    def add_edge(self, node, neighbor):
        """เพิ่มเส้นเชื่อมแบบไม่ถ่วงน้ำหนัก (Undirected, Unweighted)"""
        if node not in self.graph:
            self.graph[node] = []
        if neighbor not in self.graph:
            self.graph[neighbor] = []

        self.graph[node].append(neighbor)
        self.graph[neighbor].append(node)

    def show_graph(self):
        """แสดงโครงสร้างกราฟ"""
        for node, neighbors in self.graph.items():
            print(f"{node} => {neighbors}")

    def plot_graph(self, highlight_nodes=None, title="Graph Structure"):
        """วาดกราฟด้วย NetworkX"""
        G = nx.Graph()
        for node in self.graph:
            for neighbor in self.graph[node]:
                G.add_edge(node, neighbor)

        pos = nx.spring_layout(G, seed=42)
        plt.figure(figsize=(6, 4))

        node_colors = []
        for n in G.nodes():
            if highlight_nodes and n in highlight_nodes:
                node_colors.append("lightcoral")
            else:
                node_colors.append("skyblue")

        nx.draw(
            G, pos,
            with_labels=True,
            node_color=node_colors,
            node_size=1200,
            font_size=12,
            font_weight='bold',
            edge_color='gray'
        )
        plt.title(title)
        plt.show()

    def bfs(self, start):
        """Breadth-First Search"""
        visited = set()
        queue = deque([start])
        visited_order = []

        while queue:
            node = queue.popleft()
            if node not in visited:
                visited.add(node)
                visited_order.append(node)
                queue.extend(neighbor for neighbor in self.graph[node] if neighbor not in visited)

        print("BFS Traversal:", visited_order)
        self.plot_graph(highlight_nodes=visited_order, title="BFS Traversal")

    def dfs(self, start):
        """Depth-First Search"""
        visited = set()
        visited_order = []

        def dfs_recursive(node):
            if node not in visited:
                visited.add(node)
                visited_order.append(node)
                for neighbor in self.graph[node]:
                    dfs_recursive(neighbor)

        dfs_recursive(start)
        print("DFS Traversal:", visited_order)
        self.plot_graph(highlight_nodes=visited_order, title="DFS Traversal")


if __name__ == "__main__":
    g = GraphStructure()
    g.add_edge('A', 'B')
    g.add_edge('A', 'C')
    g.add_edge('B', 'D')
    g.add_edge('C', 'D')
    g.add_edge('D', 'E')

    print("Graph Structure:")
    g.show_graph()

    g.bfs('A')
    g.dfs('A')
